os: Visual Studio 2015

platform: x64

install:
  - ps: choco install strawberryperl
  - ps: refreshenv
    # - ps: $Env:Path = "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;$Env:Path"
  - ps: . {iwr -useb https://rakubrew.org/install-on-powershell.ps1 } | iex
  - ps: $Env:Path = "C:\rakubrew\bin;$Env:Path"
  - ps: $Env:Path = "$(rakubrew home)/shims;$Env:Path"
  - ps: rakubrew mode shim
  - ps: rakubrew download
  - ps: git clone https://github.com/ugexe/zef.git
  - ps: dir C:\rakubrew
  - ps: rakubrew build zef
  - ps: cd $Env:APPVEYOR_BUILD_FOLDER
  - ps: zef --verbose --deps-only install .

build: off

test_script:
  - prove -v -e "raku -Ilib" t/

shallow_clone: true
